name: PlayerWeight
main: me.NoChance.PlayerWeight.PlayerWeight
version: 1.1
author: NoChanceSD
description: Add weight to every item.

commands:
   pw:
      description: Main SoulsLoad Command
      
permissions:
   playerweight.*:
     description: Gives access to all PlayerWeight features
     default: op
     children:
       playerweight.debug: true
       playerweight.reload: true
   playerweight.debug:
     description: Allow use of the debug command
     default: false
   playerweight.reload:
     description: Allow the reload of PlayerWeight
     default: false